"""initial tables

Revision ID: 917c30869a79
Revises: 
Create Date: 2026-08-06 16:16:11.753746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '917c30869a79'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_table('browser_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_browser_sessions_status'), 'browser_sessions', ['status'], unique=False)
    op.create_table('job_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_results_task_id'), 'job_results', ['task_id'], unique=True)
    op.create_table('timeline_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('browser_session_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['browser_session_id'], ['browser_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_events_browser_session_id'), 'timeline_events', ['browser_session_id'], unique=False)
    op.create_index(op.f('ix_timeline_events_task_id'), 'timeline_events', ['task_id'], unique=False)
    op.create_index('ix_timeline_events_task_id_event_type', 'timeline_events', ['task_id', 'event_type'], unique=False)
    op.drop_index(op.f('idx_credit_log_user'), table_name='credit_log')
    op.drop_table('credit_log')
    op.drop_index(op.f('idx_repo_members_user'), table_name='repo_members')
    op.drop_table('repo_members')
    op.drop_table('user_credits')
    op.drop_index(op.f('idx_messages_session'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('recipes')
    op.drop_table('persisted_repos')
    op.drop_index(op.f('idx_custom_agents_repo'), table_name='custom_agents')
    op.drop_table('custom_agents')
    op.drop_index(op.f('idx_recipe_runs_session'), table_name='recipe_runs')
    op.drop_table('recipe_runs')
    op.drop_index(op.f('idx_user_repos_user'), table_name='user_repos')
    op.drop_table('user_repos')
    op.drop_table('user_llm_settings')
    op.drop_table('conversations')
    op.drop_index(op.f('idx_payments_order'), table_name='payments')
    op.drop_index(op.f('idx_payments_user'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('idx_metrics_name'), table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('idx_cache_hash'), table_name='semantic_cache')
    op.drop_table('semantic_cache')
    op.drop_table('file_snapshots')
    op.drop_table('user_limits')
    op.drop_index(op.f('idx_repo_owner'), table_name='repos')
    op.drop_table('repos')
    op.drop_index(op.f('idx_trace_id'), table_name='trace_events')
    op.drop_index(op.f('idx_trace_session'), table_name='trace_events')
    op.drop_table('trace_events')
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_provider'), table_name='users')
    op.drop_table('users')
    op.drop_table('graph_changelog')
    op.drop_index(op.f('idx_audit_session'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_user'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('idx_embeddings_repo'), table_name='code_embeddings')
    op.drop_table('code_embeddings')
    op.drop_index(op.f('idx_llm_usage_user'), table_name='llm_usage')
    op.drop_table('llm_usage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_usage',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('repo_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('model', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('prompt_tokens', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('completion_tokens', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('total_tokens', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('intent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('latency_ms', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('success', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('error_msg', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('llm_usage_pkey'))
    )
    op.create_index(op.f('idx_llm_usage_user'), 'llm_usage', ['user_id', 'created_at'], unique=False)
    op.create_table('code_embeddings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('repo_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('node_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('node_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('code_embeddings_pkey')),
    sa.UniqueConstraint('repo_id', 'node_id', name=op.f('code_embeddings_repo_id_node_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_embeddings_repo'), 'code_embeddings', ['repo_id', 'node_type'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('repo_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('intent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('latency_ms', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey'))
    )
    op.create_index(op.f('idx_audit_user'), 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_audit_session'), 'audit_logs', ['session_id', 'created_at'], unique=False)
    op.create_table('graph_changelog',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('repo_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('change_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('nodes_added', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('nodes_removed', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('indexed_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('graph_changelog_pkey'))
    )
    op.create_table('users',
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('provider', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('provider_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('avatar_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('oauth_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('users_pkey')),
    sa.UniqueConstraint('email', name=op.f('users_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_users_provider'), 'users', ['provider', 'provider_id'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.create_table('trace_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('trace_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('agent', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('tool_name', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('input_data', sa.TEXT(), server_default=sa.text("'{}'::text"), autoincrement=False, nullable=True),
    sa.Column('output_data', sa.TEXT(), server_default=sa.text("'{}'::text"), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'success'::text"), autoincrement=False, nullable=True),
    sa.Column('latency_ms', sa.REAL(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('token_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('error', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('seq', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('trace_events_pkey'))
    )
    op.create_index(op.f('idx_trace_session'), 'trace_events', ['session_id', 'seq'], unique=False)
    op.create_index(op.f('idx_trace_id'), 'trace_events', ['trace_id'], unique=False)
    op.create_table('repos',
    sa.Column('repo_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('graph_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'active'::text"), autoincrement=False, nullable=True),
    sa.Column('node_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('repo_id', name=op.f('repos_pkey'))
    )
    op.create_index(op.f('idx_repo_owner'), 'repos', ['owner_id'], unique=False)
    op.create_table('user_limits',
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('plan', sa.TEXT(), server_default=sa.text("'free'::text"), autoincrement=False, nullable=False),
    sa.Column('max_repos', sa.INTEGER(), server_default=sa.text('3'), autoincrement=False, nullable=False),
    sa.Column('max_repo_size_mb', sa.INTEGER(), server_default=sa.text('100'), autoincrement=False, nullable=False),
    sa.Column('max_messages_day', sa.INTEGER(), server_default=sa.text('50'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.TEXT(), server_default=sa.text("'system'::text"), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('user_limits_pkey'))
    )
    op.create_table('file_snapshots',
    sa.Column('repo_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content_hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('indexed_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('node_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('repo_id', 'file_path', name=op.f('file_snapshots_pkey'))
    )
    op.create_table('semantic_cache',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('query_hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('query_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('response', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('semantic_cache_pkey'))
    )
    op.create_index(op.f('idx_cache_hash'), 'semantic_cache', ['session_id', 'query_hash'], unique=False)
    op.create_table('metrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('metric_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metric_value', sa.REAL(), autoincrement=False, nullable=False),
    sa.Column('tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('metrics_pkey'))
    )
    op.create_index(op.f('idx_metrics_name'), 'metrics', ['metric_name', 'created_at'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('razorpay_order_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('razorpay_payment_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('razorpay_signature', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('plan_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('amount_paise', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('credits_added', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('unlimited_granted', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'created'::text"), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('verified_at', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('payments_pkey')),
    sa.UniqueConstraint('razorpay_order_id', name=op.f('payments_razorpay_order_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_payments_user'), 'payments', ['user_id'], unique=False)
    op.create_index(op.f('idx_payments_order'), 'payments', ['razorpay_order_id'], unique=False)
    op.create_table('conversations',
    sa.Column('session_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('repo_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('session_id', name=op.f('conversations_pkey'))
    )
    op.create_table('user_llm_settings',
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('openai_key', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('anthropic_key', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('openrouter_key', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('gemini_key', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('preferred_model', sa.TEXT(), server_default=sa.text("'meta-llama/llama-3.3-70b-instruct:free'::text"), autoincrement=False, nullable=True),
    sa.Column('router_model', sa.TEXT(), server_default=sa.text("'mistralai/mistral-7b-instruct:free'::text"), autoincrement=False, nullable=True),
    sa.Column('use_own_keys', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('user_llm_settings_pkey'))
    )
    op.create_table('user_repos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('repo_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('git_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('git_branch', sa.TEXT(), server_default=sa.text("'main'::text"), autoincrement=False, nullable=True),
    sa.Column('repo_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'READY'::text"), autoincrement=False, nullable=True),
    sa.Column('overview', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('last_used', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('user_repos_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_repos_pkey')),
    sa.UniqueConstraint('user_id', 'repo_id', name=op.f('user_repos_user_id_repo_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_user_repos_user'), 'user_repos', ['user_id'], unique=False)
    op.create_table('recipe_runs',
    sa.Column('run_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('recipe_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('repo_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'running'::text"), autoincrement=False, nullable=True),
    sa.Column('current_step', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('total_steps', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('results', sa.TEXT(), server_default=sa.text("'[]'::text"), autoincrement=False, nullable=True),
    sa.Column('error', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('started_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('finished_at', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('run_id', name=op.f('recipe_runs_pkey'))
    )
    op.create_index(op.f('idx_recipe_runs_session'), 'recipe_runs', ['session_id'], unique=False)
    op.create_table('custom_agents',
    sa.Column('agent_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('repo_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('system_prompt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('triggers', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('capabilities', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('agent_id', name=op.f('custom_agents_pkey'))
    )
    op.create_index(op.f('idx_custom_agents_repo'), 'custom_agents', ['repo_id', 'is_active'], unique=False)
    op.create_table('persisted_repos',
    sa.Column('repo_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('git_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('git_branch', sa.TEXT(), server_default=sa.text("'main'::text"), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'READY'::text"), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('overview', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('repo_id', name=op.f('persisted_repos_pkey'))
    )
    op.create_table('recipes',
    sa.Column('recipe_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('repo_id', sa.TEXT(), server_default=sa.text("'*'::text"), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('steps', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_builtin', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.TEXT(), server_default=sa.text("'system'::text"), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('recipe_id', name=op.f('recipes_pkey'))
    )
    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('role', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('intent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['conversations.session_id'], name=op.f('messages_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('messages_pkey'))
    )
    op.create_index(op.f('idx_messages_session'), 'messages', ['session_id', 'created_at'], unique=False)
    op.create_table('user_credits',
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('credits', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('unlimited', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('total_used', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('user_credits_pkey'))
    )
    op.create_table('repo_members',
    sa.Column('repo_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('role', sa.TEXT(), server_default=sa.text("'viewer'::text"), autoincrement=False, nullable=False),
    sa.Column('added_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('repo_id', 'user_id', name=op.f('repo_members_pkey'))
    )
    op.create_index(op.f('idx_repo_members_user'), 'repo_members', ['user_id'], unique=False)
    op.create_table('credit_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('delta', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('admin_id', sa.TEXT(), server_default=sa.text("'system'::text"), autoincrement=False, nullable=True),
    sa.Column('balance_after', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('credit_log_pkey'))
    )
    op.create_index(op.f('idx_credit_log_user'), 'credit_log', ['user_id'], unique=False)
    op.drop_index('ix_timeline_events_task_id_event_type', table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_task_id'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_browser_session_id'), table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index(op.f('ix_job_results_task_id'), table_name='job_results')
    op.drop_table('job_results')
    op.drop_index(op.f('ix_browser_sessions_status'), table_name='browser_sessions')
    op.drop_table('browser_sessions')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
